name: Testing on push

on: push

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest
    env:
      DBUSER: ${{secrets.DBUSER}}
      DBPASSWORD: ${{secrets.DBPASSWORD}}
      DBNAMETEST: ${{secrets.DBNAMETEST}}
      PORT: ${{secrets.PORT}}
      SECRET: ${{secrets.SECRET}}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm run test
